language: csharp

matrix:
  include:
    - dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
    - mono: latest
install:
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  - nuget install Castle.Core
  - nuget install Moq
script:
  - xbuild /p:Configuration=Release ./MyNewService/MyNewService.csproj
  - xbuild /p:Configuration=Release ./UnitTestProj/UnitTestProj.csproj
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./UnitTestProj/bin/release/UnitTestProj.dll
