language: csharp

matrix:
  include:
    - dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
    - mono: latest
install:
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  - nuget install Castle.Core
  - nuget install Moq
script:
  - xbuild /p:Configuration=Release ./MyNewService/MyNewService.csproj
  - nunit-console ./UnitTestProj/bin/Debug/UnitTestProj.dll
